---
- name: Install apache package
  dnf:
    name: httpd
    state: present

- name: Configure firewall
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    service: http
  #when: "{{ inventory_hostname}} in groupnames['webservers']"

- template:
    src: index.j2
    dest: /var/www/html/index.html
...

