---
- name: Capitalize, upper and lower filter
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Calculate total/sum
    debug:
        msg: "{{ [20, 34, 16, 80, 100, 12] | sum }}"

  - name: Find the largest value
    debug:
        msg: "{{ [20, 34, 16, 80, 100, 12] | max }}"

  - name: Find the largest value
    debug:
        msg: "{{ [20, 34, 16, 80, 100, 12] | min }}"


