---
- name: Create user using users-list.txt and dynamically assigned hash password
  become: true
  hosts: webservers

  vars:
  - hpass: "{{ 'redhat' | password_hash('sha512') }}"

  vars_files: users-list.txt

  tasks:
  - group:
     name: "{{ item }}"
    loop:
    - test
    - dev

  - user:
     name: "{{ item.name }}"
     group: "{{ item.groupn }}"
     password:  "{{ hpass }}"
    loop: "{{ users }}"
...
