---
- name: Create user using users-list.txt and dynamically assigned hash password
  become: true
  hosts: localhost

  vars:
   hpass: "{{ 'redhat' | password_hash('sha512') }}"

  vars_files: 
  - files/users-list.txt
  - files/groups-list.txt

  tasks:
  - ansible.builtin.group:
     name: "{{ item.groupname }}"
    loop: "{{ users }}"

  - ansible.builtin.user:
     name: "{{ item.username }}"
     group: "{{ item.groupname }}"
     password:  "{{ hpass }}"
    loop: "{{ users }}"
...
