- name: This is going to display some messages
  hosts: localhost
  tasks:
  - name: task 1....
    debug:
      msg: hello world
  - name: task 2....
    debug:
      msg: hello world
  - debug:
      msg: hello world

