---
- name: Install web server
  hosts: all
  become: true
  vars:
   packages:
    - mod_ssl
    - vim
    - httpd

  tasks:
  # This is for hr, ......
  # .....
  # ....
  - name: Install pckgs
    dnf:
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}" 

  - name: Start the service
    service:
      name: httpd
      state: started
      enabled: yes
...
