---
- name: Install pacakges based on hosts
  hosts: dev,test,prod
  
  tasks:
  - dnf:
      name: mariadb,php
      state: present
  
- name: Install packages into dev group
  hosts: dev

  tasks:
  - dnf:
      name: "@RPM Development Tools"
      state: present

  - dnf:
      name: "*"
      state: latest
...    
