---
- name: Use lookup plug-ins
  hosts: localhost
  gather_facts: no
  vars:
    hosts: "{{ query('ansible.builtin.file', '/etc/hosts') }}"
    readme: "{{ query('ansible.builtin.file', '/etc/hosts', '/etc/resolv.conf') }}"

  tasks:
  - name: Show content of hosts variable
    copy:
      content: "{{ hosts }}"
      dest: hosts-by-lookup

  - name: Show content of readme variable
    copy:
      content: "{{ readme }}"
      dest: readme-by-lookup
