- name: Validate web service configuration
  hosts: localhost
  tasks:
  - name: testing changed_when
    command:
      cmd: touch /tmp/file1
    changed_when: false
    register: cmd_status
    notify: notifyme


  handlers:
  - name: notifyme
    debug:
      var: cmd_status
