---
# Sandbox Cisco DNA Center credentials
catalystcenter_host: "sandboxdnac2.cisco.com"
catalystcenter_port: 443
catalystcenter_username: "devnetuser"
catalystcenter_password: "Cisco123!"
catalystcenter_version: 3.1.6.0
catalystcenter_verify: false
catalystcenter_debug: true
catalystcenter_log_level: [CRITICAL, ERROR, WARNING, INFO, DEBUG]
catalystcenter_log_file_path: /var/log/dnac.log
catalystcenter_log_append: true


# catalystcenter_host: sandboxdnac.cisco.com
# catalystcenter_api_port: 443
# catalystcenter_username: devnetuser
# catalystcenter_password: Cisco123!
# catalystcenter_version: "3.1.3.0"
# catalystcenter_verify: False
# catalystcenter_debug: True
# catalystcenter_log_level: [CRITICAL, ERROR, WARNING, INFO, DEBUG]
# catalystcenter_log_file_path: /var/log
# catalystcenter_log_append: True
