---
- name: Play
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/credentials.yml
  tasks:
    - name: Get site info and updating site details
      cisco.catalystcenter.site_intent:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        catalystcenter_log: true
        state: merged
        config:
          - site:
              floor:
                name: Test_Floor2
                parent_name: 'Global/USA/San Francisco/BGL_18'
                length: "101"
                width: "75"
                height: "50"
                rf_model: 'Cubes And Walled Offices'
                floor_number: 3
          - site:
              area:
                name: Canada
                parent_name: 'Global'
            type: area
