---
- name: Play
  hosts: localhost
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  connection: local
  tasks:
    - name: Import Local
      cisco.catalystcenter.swim_import_local:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_port: "{{ catalystcenter_port }}"
        catalystcenter_version: "{{ catalystcenter_version }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        # headers: "{{ my_headers | from_json }}"
        isThirdParty: false
        thirdPartyVendor: "string"
        thirdPartyImageFamily: "string"
        thirdPartyApplicationType: "string"
        filePath: "./tests/test-1592357065255.csv"
      register: result
