---
- name: Play
  hosts: localhost
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  tasks:
    - name: Create tag with name "MyNewTag"
      cisco.catalystcenter.tag:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        state: present
        description: My Tag
        name: MyNewTag
      register: result
    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
    - name: Get task status
      cisco.catalystcenter.task_info:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        taskId: "{{ result.catalystcenter_response.response.taskId }}"
      when:
        - result.catalystcenter_response is defined
        - result.catalystcenter_response.response is defined
        - result.catalystcenter_response.response.taskId is defined
      register: task_result
    - name: Show status of create tag operation
      ansible.builtin.debug:
        msg: "{{ task_result.catalystcenter_response.response }}"
      when:
        - task_result is defined
        - task_result.catalystcenter_response is defined
    - name: Create the same tag
      cisco.catalystcenter.tag:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        state: present
        description: My Tag 1
        name: MyNewTag
      register: result
    - name: Get task status
      cisco.catalystcenter.task_tree_info:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        taskId: "{{ result.catalystcenter_response.response.taskId }}"
      when:
        - result.catalystcenter_response is defined
        - result.catalystcenter_response.response is defined
        - result.catalystcenter_response.response.taskId is defined
      register: task_tree_result
    - name: Show status of update tag operation
      ansible.builtin.debug:
        msg: "{{ task_tree_result.catalystcenter_response.response }}"
      when:
        - task_tree_result is defined
        - task_tree_result.catalystcenter_response is defined
    - name: Get tag with name "MyNewTag"
      cisco.catalystcenter.tag_info:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        name: MyNewTag
      register: result
    - name: Show tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"
    - name: Delete tag
      cisco.catalystcenter.tag:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        state: absent
        name: MyNewTag
      register: result
    - name: Show deleted tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"
    # - name: Get task status
    #   cisco.catalystcenter.task_info:
    #     catalystcenter_host: "{{ catalystcenter_host }}"
    #     catalystcenter_username: "{{ catalystcenter_username }}"
    #     catalystcenter_password: "{{ catalystcenter_password }}"
    #     catalystcenter_verify: "{{ catalystcenter_verify }}"
    #     taskId: "{{ result.catalystcenter_response.response.taskId }}"
    #   when:
    #     - result.catalystcenter_response is defined
    #     - result.catalystcenter_response.response is defined
    #     - result.catalystcenter_response.response.taskId is defined
    #   register: task_tree_result

    # - name: Show status of delete tag operation
    #   debug:
    #     msg: "{{ task_tree_result.catalystcenter_response.response }}"
    #   when:
    #     - task_tree_result is defined
    #     - task_tree_result.catalystcenter_response is defined
    - name: Get tag with name "MyNewTag"
      cisco.catalystcenter.tag_info:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        name: MyNewTag
      register: result
    - name: Show tags with name "MyNewTag"
      ansible.builtin.debug:
        msg: "{{ result }}"
