---
- name: Play
  hosts: localhost
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  tasks:
    - name: Create an configuration_template_project
      cisco.catalystcenter.configuration_template_project:
        catalystcenter_host: "{{ catalystcenter_host }}"
        catalystcenter_username: "{{ catalystcenter_username }}"
        catalystcenter_password: "{{ catalystcenter_password }}"
        catalystcenter_verify: "{{ catalystcenter_verify }}"
        catalystcenter_debug: "{{ catalystcenter_debug }}"
        state: present
        name: Cloud Test Template 5
      register: configuration_template_project_result
    - name: Show new configuration_template_project
      ansible.builtin.debug:
        msg: "{{ configuration_template_project_result }}"
      when:
        - configuration_template_project_result is defined
