---
- name: Collect information
  become: true
  hosts: all

  tasks:
  - name: use template from list-hw-req.j2
    template: 
      src: hwrequire.j2
      dest: /tmp/hwrequire.txt
...

