- name: Example of chapter 05 using loop with condition
  hosts: localhost
  vars:
    fruits:
    - apple
    - banana
    - carrot
    - banana
    - apple
    - orange
    - carrot
    - orange
    - durian
    - durian

  tasks:
  - name: Using template module
    template:
      src: jinja2-indent.j2
      dest: /tmp/jinja2-for-count.txt

